"""name2username

Revision ID: 2a77a8c5c4cd
Revises: 07bba80d924c
Create Date: 2017-09-07 16:22:43.523497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a77a8c5c4cd'
down_revision = '07bba80d924c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name', new_column_name='username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username', new_column_name='name')
    # ### end Alembic commands ###
