"""用户密码

Revision ID: 824e6097ab92
Revises: 
Create Date: 2017-09-07 16:15:40.850978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824e6097ab92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
